from . import BASE_DIR

LOGGER_DATABASE_NAME = "logger"
TEST_LOGGER_DATABASE_NAME = "test_logger"
PROD_DATABASE_NAME = "prod"
TEST_DATABASE_NAME = "test"

SQLALCHEMY_DRIVER = "sqlite+aiosqlite"

DATABASES_DIRNAME = BASE_DIR / "data"
DATABASES = {
    LOGGER_DATABASE_NAME: f"{SQLALCHEMY_DRIVER}:///data/{LOGGER_DATABASE_NAME}.db",
    TEST_LOGGER_DATABASE_NAME: f"{SQLALCHEMY_DRIVER}:///data/{TEST_LOGGER_DATABASE_NAME}.db",
    PROD_DATABASE_NAME: f"{SQLALCHEMY_DRIVER}:///data/{PROD_DATABASE_NAME}.db",
    TEST_DATABASE_NAME: f"{SQLALCHEMY_DRIVER}:///data/{TEST_DATABASE_NAME}.db",
}
DATABASE_TEST_MODE = True

LOGGER_DATABASE_ECHO = True
PROD_DATABASE_ECHO = True
TEST_DATABASE_ECHO = True
